SELECT MEMBER_NAME,
       REVIEW_TEXT, 
       DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
  FROM MEMBER_PROFILE,
       REST_REVIEW
 WHERE REST_REVIEW.MEMBER_ID = (
       SELECT MEMBER_ID   
         FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
       )
   AND MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
 ORDER BY REVIEW_DATE, REVIEW_TEXT