-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
  FROM BOOK_SALES, BOOK, AUTHOR
 WHERE SALES_DATE LIKE '2022-01%'
   AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
   AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
 GROUP BY BOOK.AUTHOR_ID, CATEGORY
 ORDER BY AUTHOR_ID, CATEGORY DESC 
