-- 코드를 입력하세요
SELECT TITLE, A.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS DATE_FORMAT
  FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
 WHERE A.CREATED_DATE LIKE '2022-10%'
   AND A.BOARD_ID = B.BOARD_ID
 ORDER BY B.CREATED_DATE, TITLE